#!/usr/bin/env python3
"""B11 (stop 26) §4 step 8 — re-derive the MDE from THIS batch's control, and test the delta.

E-026/E-027's MDE table registers the primary outcome's MDE as "**transferred: ±8 %**;
re-derived from this batch's control". The transferred number is registered and is the only
pre-run figure. The re-derivation method was NOT specified before the run, so choosing one
after seeing the delta is a researcher degree of freedom. This script therefore does three
things and reports all three, rather than picking the one that decides the verdict:

  (1) the REGISTERED transferred MDE, ±8 % of the control median — the pre-run number;
  (2) a re-derived MDE = the half-width of a 95 % bootstrap interval for the CONTROL arm's
      own median, as a percentage of that median. Reading: the smallest shift that could be
      told apart from the control's own sampling noise at this n. Seed fixed, so it
      re-derives byte-identically;
  (3) an EXACT two-sided permutation test on the difference of medians — every one of the
      C(20,10) = 184 756 relabellings of the 20 runs of a task, no distributional assumption,
      no MDE at all. This one depends on no choice made after the run.

A verdict that differs between (1), (2) and (3) is reported as differing. It is not resolved
by preferring whichever reads better.

Usage:  mde-b11-batch.py <report-dir>
"""
import itertools
import json
import os
import random
import sys

SEED = 20260930
BOOT = 20000
TRANSFERRED_PCT = 8.0
# The primary registered outcome, plus the secondaries the experiments report without a verdict.
METRICS = ["ctx_total", "inputTokens", "cachedTokens", "cacheCreationTokens", "outputTokens",
           "estimatedCost", "durationMs", "modelCalls", "toolCalls",
           "cat_architecture-consistency", "cat_maintainability", "cat_test-quality",
           "cat_change-focus"]
PRIMARY = "ctx_total"


def median(v):
    v = sorted(v)
    m = len(v) // 2
    return v[m] if len(v) % 2 else (v[m - 1] + v[m]) / 2


def load(report_dir):
    path = os.path.join(report_dir, "per-run.tsv")
    with open(path) as fh:
        hdr = fh.readline().rstrip("\n").split("\t")
        rows = [dict(zip(hdr, l.rstrip("\n").split("\t"))) for l in fh if l.strip()]
    out = {}
    for r in rows:
        key = (r["task"], r["arm"])
        rec = out.setdefault(key, {m: [] for m in METRICS})
        for m in METRICS:
            v = r[m]
            if v != "null":
                rec[m].append(float(v))
    return out


def bootstrap_ci(vals, seed=SEED, n=BOOT):
    rnd = random.Random(seed)
    k = len(vals)
    meds = sorted(median([vals[rnd.randrange(k)] for _ in range(k)]) for _ in range(n))
    return meds[int(0.025 * n)], meds[int(0.975 * n)]


def exact_perm_p(a, b):
    """Two-sided exact permutation p for |median(b) - median(a)| over all relabellings."""
    pooled = a + b
    na = len(a)
    obs = abs(median(b) - median(a))
    hit = tot = 0
    idx = range(len(pooled))
    for combo in itertools.combinations(idx, na):
        s = set(combo)
        x = [pooled[i] for i in combo]
        y = [pooled[i] for i in idx if i not in s]
        tot += 1
        if abs(median(y) - median(x)) >= obs - 1e-12:
            hit += 1
    return hit / tot, tot


def main():
    report_dir = sys.argv[1]
    data = load(report_dir)
    out, lines = {}, [
        "# B11 step-8 — MDE re-derivation and permutation tests.",
        "# (1) registered transferred MDE = ±8 % of the control median (the only pre-run number).",
        f"# (2) re-derived MDE = half-width of a 95 % bootstrap CI of the CONTROL median,",
        f"#     {BOOT} resamples, seed {SEED}, expressed as % of that median.",
        "# (3) exact two-sided permutation p on the difference of medians, all C(20,10) splits.",
        "# Generated by evidence/b11/mde-b11-batch.py. Re-run it to re-derive every figure.",
        "",
    ]
    for task in ("BE-003", "BE-004"):
        c, t = data[(task, "control")], data[(task, "treated")]
        lines += [f"## {task}", "",
                  "| metric | control median | treated median | delta % | registered MDE ±8 % | "
                  "re-derived MDE (bootstrap) | inside registered? | inside re-derived? | exact perm p |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for m in METRICS:
            cv, tv = c[m], t[m]
            if not cv or not tv:
                continue
            cm, tm = median(cv), median(tv)
            d = tm - cm
            dp = None if cm == 0 else 100.0 * d / cm
            lo, hi = bootstrap_ci(cv)
            half = (hi - lo) / 2.0
            rpct = None if cm == 0 else 100.0 * half / cm
            p, tot = exact_perm_p(cv, tv)
            ins_reg = None if dp is None else abs(dp) < TRANSFERRED_PCT
            ins_red = None if (dp is None or rpct is None) else abs(dp) < rpct
            lines.append("| {} | {:g} | {:g} | {} | {} | {} | {} | {} | {:.5f} |".format(
                m, cm, tm,
                "n/a" if dp is None else f"{dp:+.2f}%",
                "n/a" if cm == 0 else f"±{0.08*cm:.4g}",
                "n/a" if rpct is None else f"±{half:.4g}  (±{rpct:.2f}%)",
                "n/a" if ins_reg is None else ("yes" if ins_reg else "NO"),
                "n/a" if ins_red is None else ("yes" if ins_red else "NO"),
                p))
            out.setdefault(task, {})[m] = {
                "control_median": cm, "treated_median": tm, "delta": d, "delta_pct": dp,
                "registered_mde_pct": TRANSFERRED_PCT, "rederived_mde_pct": rpct,
                "control_boot_ci": [lo, hi], "inside_registered_mde": ins_reg,
                "inside_rederived_mde": ins_red, "perm_p": p, "perm_splits": tot}
        lines.append("")
    with open(os.path.join(report_dir, "MDE.md"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(report_dir, "mde.json"), "w") as fh:
        json.dump(out, fh, indent=2, sort_keys=True)
    print(f"ok: wrote MDE.md and mde.json to {report_dir}; primary outcome is {PRIMARY}")


if __name__ == "__main__":
    main()
